### ISSUE TITLE
Some more changes/priorities since last commits.

### ISSUE THREAD

**Issue by Sameeranjoshi** [bitsimplify/bitsimplify#9]
Consider the priorities mentioned to left.

```
A) index page.
(p1)	1. 
	Check the benchmark results here >>
	remove >> from text.

(p2)	2.We deliver the best Development Experience
	 "know more" points to ?

(p2)	3. We support RISC-V.
	"know more" points to?

(p1)	4. Contact form:
(p1)		mobile- working?
(p1)		email ,

		The question here seems that what details should we give?
		Mobile?
		Email?  -Does the bitsimplify email work, if so, how/others can get details if someone sends mail?
		Aditya?

(can be low priority) Form submission doesn't work.
(if needs more work) 		

	links below the index page:
	1.	Development link at bottom
(p1)		https://bitsimplify.github.io/bitsimplify/docs.html

		What to do with this? Do we need it?
		Should be remove the development link from index page temporary?
	I think it's better to remove the link, we can add later if we need.


(p1)	2. https://bitsimplify.github.io/bitsimplify/privacy.html 
		Is privacy correct?
		Do we need privacy page initially?
	
	Again it's better to remove it.

(p1)	3. Terms of Servics --> privacy page.
		Do we need privacy page initially?
	Again it's better to remove it.


(p1)	4. teams -> goes to https://bitsimplify.github.io/bitsimplify/career.html
		Do we want to add more jobs/linkedin here?
		Is it needed for initial basic website?

	Who is gonna join us initially,hahaha... we can get in touch with him if the form works, so form get's more importance..
	I think better to be in  status quo.

B)
(P1) 1) Downlads page:
	Contents in Loream Ipsum.

C)
(P1) 2) Benchmark page :
	More content here?
	more info here?
	Do we need to add how did we do
	optimizations, what we used.
	More info about the process.

	Need more details from Reshabh here.
```

**Comment by skdarekar** [comment]
Need more details - @Sameeranjoshi 
1. We deliver the best Development Experience
	 "know more" points to (Link to the product page # devenv section) as per the planning doc but cannot find any reference to this section

2. We support RISC-V.
	"know more" points to (Link to the product page # compilerSAAS section) as per the planning doc but cannot find any reference to this section

**Comment by skdarekar** [comment]
- [x] Check the benchmark results here >> remove >> from text. 
- [x] We deliver the best Development Experience "know more" points to ?
- [x] We support RISC-V. "know more" points to?
- [x] Contact form - Embed google form to make it work temparory.
- [x] Development link at bottom - Hidden
- [x] https://bitsimplify.github.io/bitsimplify/privacy.html - hidden
- [x] Terms of Servics --> privacy page. -- hidden
- [x] teams -> goes to https://bitsimplify.github.io/bitsimplify/career.html - linked to bitsimplify linkedin page
- [x] Downlads page: Contents in Loream Ipsum.
- [x] Benchmark page
